### ISSUE TITLE
Revision for Tech MD: DROID on prod

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#573]
Relates to ticket #283. PUID identification is missing from FITS when tested in test and prod, but we have seen it in local/development environments.

Devanshu noted that DROID may not be running on PROD, which is where PUID is extracted from.

**Comment by mprefer** [comment]
Attempted to execute /opt/fits-1.4.0/fits.sh -i <some GZip file>. Fits threw the exception below:

2019-09-16 18:29:40 - ERROR - ToolBelt:140 - Thread 1 error initializing edu.harvard.hul.ois.fits.tools.droid.Droid: java.lang.InstantiationException  Message: edu.harvard.hul.ois.fits
.tools.droid.Droid
java.lang.InstantiationException: edu.harvard.hul.ois.fits.tools.droid.Droid
	at java.lang.Class.newInstance(Class.java:427)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.createToolClassInstance(ToolBelt.java:174)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:122)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:58)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:243)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:123)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:112)
	at edu.harvard.hul.ois.fits.Fits.constructFits(Fits.java:325)
	at edu.harvard.hul.ois.fits.Fits.main(Fits.java:307)
Caused by: java.lang.NoSuchMethodException: edu.harvard.hul.ois.fits.tools.droid.Droid.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 8 more

**Comment by mprefer** [comment]
Downloaded a fresh copy of 'fits-1.4.0.zip' from the Harvard FITS website, unzipped the contents, execute the same command as above. Here is the XML output (note the highlighted line with the PUID):

![fits.png](https://images.zenhubusercontent.com/5c12be5f7387c610cbb20714/63511e90-6678-4cca-94cb-00a507f1c457)

Ran an md5sum on all the files in the original FITS directory and the new FITS directory. All files have the same checksums. So, I don't have an explanation for the original Droid exception.

**Comment by mprefer** [comment]
Ooops, spoke too soon. Found the culprit in the <FITS_Home>/xml/fits.xml.

From the fits.xml file from the existing install:
<droid_sigfile>DROID_SignatureFile_V90.xml</droid_sigfile>

From the fits.xml file from the new install:
<droid_sigfile>DROID_SignatureFile_V94_Alt.xml</droid_sigfile>

**Comment by eporter23** [comment]
@mprefer @devanshu-m confirmed - we have PUID!

![Screen Shot 2019-09-17 at 11.53.25 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a0f1c2df-81bc-4bdf-9525-0ffc28c615ab)
